### ISSUE TITLE
v0.17 broke it!

### ISSUE THREAD

**Issue by Gitoffthelawn** [stoically/firefox-add-on-temporary-containers#13]
v0.17 seems to have broken it under FF v58beta12 with Win7.

Pressing the toolbar button no longer opens up a new container.  No settings were changed since the previous version.

**Comment by stoically** [comment]
Thanks for reporting and sorry for breaking. Unfortunately this affected a part of the code which is hard to cover with test (external triggering of Event Listeners), but I will look into adding tests for that, so it won't happen again - since that's like the core functionality that should always work.

Version 0.18 with the fix is published. Please let me know if there's still something not working as expected.

**Comment by Gitoffthelawn** [comment]
The new version fixed it.  Thanks!
