### ISSUE TITLE
Keyboard shortcut to open new Tab in the same container that currently is active

### ISSUE THREAD

**Issue by stoically** [stoically/firefox-add-on-temporary-containers#33]

**Comment by anewuser** [comment]
It'd be great if this could happen with <kbd>Alt</kbd> + <kbd>T</kbd> (https://github.com/mozilla/multi-account-containers/issues/462). That's how Private Tabs worked.

**Comment by stoically** [comment]
On some Linux distributions (including mine) <kbd>Alt</kbd> + <kbd>T</kbd> (TIL that `<kbd>` exists :D) opens the "Tools" menu - so I can't use that one unfortunately.

**Comment by anewuser** [comment]
I meant <kbd>Ctrl</kbd> + <kbd>T</kbd>*, sorry.

**Comment by stoically** [comment]
Personally I have the feeling that this is a bit against the philosophy of this Add-on to use throw-away containers as often as possible. But I guess adding it as advanced preference doesn't hurt.

**Comment by anewuser** [comment]
This is mainly because I want the same shortcut to:
* open another normal tab if I used it in a normal tab
* open another containerized tab if I used it a in a containerized tab

Right now it's either this or that.

**Comment by stoically** [comment]
Yeah, I totally understand why one would like that behavior - and I will add it.

I'm curious, what's your reason to not always by default use a throw-away container and just bind those that you need to have persistent storage to permanent containers using Multi-Account Containers?

**Comment by anewuser** [comment]
That would leave me with almost no history, since I've set containers created with your extension to erase history entries.

**Comment by stoically** [comment]
Ok, I understand. Do you maybe have an idea what could support you in using disposable containers as a default? Just trying to figure out an UX sweetspot. :)

**Comment by anewuser** [comment]
The thing is that I also use Cookie AutoDelete and block third-party cookies, and in practice that's almost the same as having isolated temporary containers for everything but whitelisted items. 

I could use your extension with disposable containers by default and uninstall Cookie AutoDelete, but then I'd have to disable its history cleanup and install and use Multi-Account Containers to manage the cookie/storage whitelist. I've never installed it. The container feature was enabled under the hood along with your extension.

**Comment by stoically** [comment]
I see, thanks for the explanation. Yeah, actually I also have CAD and blocked third-party cookies. Although that's already pretty solid privacy, what's missing compared to disposable containers is the isolation of cookies and storage while browsing: e.g. you open a link to an item on a shopping site in one tab, keep that open, and a little bit later open a link to another item on the same shopping site - it's now clear to the site that you saw both items. Though in practice some sites might go to the extend to match that visit with fingerprinting, it still makes it harder to track you. That's why I additionally use throw-away containers.

What's nice about having websites bound to specific permanent containers with Multi-Account Containers that it gives you a choice for some sites and reminds you: "Do I want to see that site see that particular visit easily now and associate it with the account I'm logged in with or should I use a temporary container instead" (think visiting random profiles or repositories on social-media sites/github).

Another small but nice thing is that when middle-mouse / ctrl+left clicking links to open in a temporary container it'll automatically strip the referer - but of course you can achieve that with Firefox configuration or other Add-ons too.

**Comment by stoically** [comment]
Oh, and one minor thing: With localStorage support enabled in CAD you make fingerprinting easier, because [CAD needs to set a cookie for the domains](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enable-localstorage-support). You don't have that with disposable containers.

**Comment by stoically** [comment]
Since you got me curious, I've also tested CAD regarding indexedDB storage - and CAD can't clean that either.

If you want to see it yourself try filling your indexedDB and localStorage with 5kb on this site: https://demo.agektmr.com/storage/
Now close the tab (and click Clean depending on your settings), open the site again and you'll see that the indexedDB storage is still there.

**Comment by stoically** [comment]
Unfortunately it wasn't possible to implement an overwrite for Ctrl+T to open a Tab in the same container as the currently active one. It's virtually impossible to keep track of the "real last active tab" - I mean, maybe it's possible, but I invested quite some time and it seems hard. Maybe I give it another shot one day.

Until then there'll be the <kbd>Alt</kbd>+<kbd>X</kbd> keyboard shortcut in the next release to support opening Tabs in the currently active container.

**Comment by stoically** [comment]
Just published version 0.33 with the keyboard shortcut.

**Comment by anewuser** [comment]
>you open a link to an item on a shopping site in one tab, **keep that open**

In my opinion, that's not a problem if it happens only when I open two tabs at the same time or within 10 minutes. Whatever cookie/storage-based suggestion system they have in place might actually benefit me at that moment, but won't affect me the next time I open their site. 

Anyway, you'd have to go as far as using random user-agents and different proxies for each HTTP(s) request to be completely sure they can't know you've accessed two different pages.

> CAD: With localStorage support enabled you make fingerprinting easier

I've made [this quick test page](https://anewuser.github.io/dom-examples/web-storage/index.html), and you're right that we can be tracked. [I've reported this to Cookie AutoDelete](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44#issuecomment-363183067) and suggested them to use random allowed paths. 

> Multi-Account Containers is that it gives you a choice 

Since Opera Presto, I'm used to using regular tabs for accounts with my permanent cookies, and private tabs for secondary accounts etc. No questions asked, and no extra list to maintain. I think that using both Multi-Account Containers/temp by default  and Cookie AutoDelete is an overkill, since you basically have to whitelist the same domain twice to remember your permanent logins and then choose the container.

With the Firefox Private Tab extension, I had actually set most of my custom searches/bookmarks with keywords to open automatically in private tabs with the `private:` pseudo-protocol, so for some time I did browse everything opened from search engines in a unified temporary container by default, but that had the downside of my losing all pages I wanted to open again but forgot to bookmark. That would happen if I used no-history containers by default too.

Now, it turned out you were right about [Historia being light on resources](https://github.com/stoically/firefox-add-on-temporary-containers/issues/17#issuecomment-361010363), and it supports regex entries like `/\/?q=/`, so using it  along with your extension is even better than what I had before. 

> it'll automatically strip the referer 

I actually also have uMatrix, which takes care of referers, and is also one of the reasons why I want to avoid another extension that requires regular interaction. 

> indexedDB storage - and CAD can't clean that

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/171

>Until then there'll be the <kbd>Alt</kbd>+<kbd>X</kbd>

I don't want to use another shortcut, but as a workaround for the few times I need to open the same container (e.g. when I'm logged to a different Gmail account and want to open its associated Youtube account in another tab), I can just open some link from the active tab in a new tab, or right-click the tab title and use the "duplicate" option.

**Comment by stoically** [comment]
> Whatever cookie/storage-based suggestion system they have in place might actually benefit me at that moment

Sure, if that's the desired behavior, then not having isolated first-party cookies through containers comes in handy.

> Anyway, you'd have to go as far as using random user-agents and different proxies for each HTTP(s) request to be completely sure they can't know you've accessed two different pages.

Even then - with browser fingerprinting it's still possible to recognize you. You'd literally have to use different hardware, configurations and some sort of proxy/anonymizer.

>  I've reported this to Cookie AutoDelete and suggested them to use random allowed paths.

I'm actually subscribed to that issue and saw your reply. Cool idea!

> I think that using both Multi-Account Containers/temp by default and Cookie AutoDelete is an overkill

It of course comes down to the individual preferences and the amount of work and time one is willing to invest in something that - in the light of browser fingerprinting - is still not the most rewarding activity.

> With the Firefox Private Tab extension, I had actually set most of my custom searches/bookmarks with keywords to open automatically in private tabs with the private: pseudo-protocol

I guess I could look into supporting special bookmarks too. If that's of interest for you, feel free to open an Issue. An alternative would be to use the "Always open in" feature that's already available - but I guess that's one list more to maintain.

> I actually also have uMatrix

Good choice!

> or right-click the tab title and use the "duplicate" option.

Didn't know about that one, ha. Cool! Yeah, sorry that it didn't worked out with overwriting - maybe #29 is implemented it's easier to try that again.

**Comment by anewuser** [comment]
Something like `private:` is impossible right now (https://bug623317.bugzilla.mozilla.org/show_bug.cgi?id=1271553), but Historia and your "Always per Site"  option already cover everything I had with it.

What you may consider adding for Firefox 59+ is a context menu entry for bookmarks: https://github.com/mozilla/multi-account-containers/issues/323#issuecomment-358548483.

**Comment by stoically** [comment]
Ah, that's great to know! Then I guess you're probably in favour of implementing #32 to make adding entries to that list even more easy? :)

Good idea, bookmarked that Issue.

**Comment by anewuser** [comment]
The toolbar idea may be useful, but it depends on how you design it and how you organize the options.  Too many settings may be too confusing for the less advanced users who would benefit the most from using your extension for not having other privacy settings and extensions enabled.  

I just read that @seansfkelley is the person behind the UI of Cookie AutoDelete. Paging him to see if he's interested in your project and would be able to help you organize everything.

It'd also be nice to keep a simple icon for opening a new temp container with a single click, so users can choose between the one with the popup and the simple "please just open a container" button. Are extensions still able to add two items like that and hide one under the Customize page by default?

**Comment by stoically** [comment]
Yeah, I agree, the popup should have a solid UI/UX (unlike parts of the preferences right now, hehe). I'll post my progress in #32 and of course would be happy about some help.

To my knowledge it's not possible to have two BrowserActions with WebExtensions, no. It might be possible to add an additional PageAction though (those show up right-hand in the address bar).

**Comment by stoically** [comment]
Btw, just realized that middle mouse clicking on the default new tab icon opens a new tab in the currently active container

**Comment by anewuser** [comment]
This doesn't seem to be compatible with Temporary Containers, but claims to make <kbd>Ctrl</kbd> + <kbd>T</kbd> open new tabs in the same container: 

https://addons.mozilla.org/addon/sticky-containers/
https://github.com/kemayo/firefox-sticky-containers
