### ISSUE TITLE
Feature-Request: Don't open about:newtab in temporary container

### ISSUE THREAD

**Issue by HeikoAdams** [stoically/firefox-add-on-temporary-containers#36]
Hi,
it would nice if about:newtab isn't opened in a temporary container (maybe via an option) because this creates some annoying flickering if you open a page from there which is set-up to use a specific container.

**Comment by stoically** [comment]
Hi, you can do that by deactivating the "Automatic Mode" in the preferences. Hope that helps.

**Comment by HeikoAdams** [comment]
Or more general: all about: urls - I don't see an advantage in containering them.

**Comment by stoically** [comment]
I see. That makes sense - glad you want to use Automatic Mode.

It's actually an interesting UX question. I feel like that opening a new Tab and seeing that it actually is already inside a Temporary Container feels good - at least for me. When disabling that you get the flickering on first navigation instead of when opening the Tab. I'll look into adding it as preference - not sure about making it a default tho.

**Comment by stoically** [comment]
One thing that might make it worth a default setting is that sometimes when the reopening of a New Tab isn't fast enough and you already started typing into the address bar, what you typed will disappear and you have to start over. That actually annoyed me from time to time.

**Comment by stoically** [comment]
Just published version 0.33 with the feature. Hope you like it. Please let me know if something doesn't work as expected.

**Comment by stoically** [comment]
This is now default with version 0.39

**Comment by stoically** [comment]
Turns out that about:newtabs sets a cookie in the container it gets opened in depending on the search-engine used - so with the "Don't reopen tabs"-configuration, those cookies are permanent in the default-container. This happens for default-search-engines in Firefox: Google, Yahoo, Bing and Wikipedia. This doesn't happen with e.g. startpage.

![gcookie](https://user-images.githubusercontent.com/29637501/36495069-f7e71714-172b-11e8-9705-6f4971613027.gif)

I'm going to change the default back to "Reopen" and force all users that currently have "Don't reopen" back to "Reopen". The preference will have a warning attached explaining that you should trust your search-engine to not set a cookie and that most will set a cookie.

**Comment by stoically** [comment]
Affected users (with Automatic Mode on and "Don't reopen" active) will see this notification upon update to the upcoming version 0.58:

![image](https://user-images.githubusercontent.com/29637501/36509655-41c6dc9e-1758-11e8-83b4-fb02e1011314.png)

**Comment by stoically** [comment]
Published version 0.58 accordingly
