### ISSUE TITLE
Deletes History containers don't respect Automatic Mode setting

### ISSUE THREAD

**Issue by chiraag-nataraj** [stoically/firefox-add-on-temporary-containers#59]
- Temporary Containers Version: 0.56
- Firefox Version: 59.0b4
- Operating System + Version: Debian sid/experimental
- Non-default Options/Preferences in Temporary Containers: 
    * Automatic Mode enabled
    * Notifications enabled
    * All options in Mouse Clicks -> Global enabled
    * Advanced -> General -> all keyboard shortcuts enabled
    * Advanced -> Delete History -> All options open delete history containers instead of normal temporary containers.
- Other installed Add-ons + Version:
    * Cookie AutoDelete 2.1.2
    * Decentraleyes 2.0.2
    * Firefox Multi-Account Containers 5.0.1
    * HTTPS Everywhere 2018.1.29
    * IDN-Warner 1.0
    * Request Control 1.8.6
    * uBlock Origin 1.15.6
    * uMatrix 1.3.2
    * WebAPI Manager 0.9.27

### Actual behavior

When I open a new tab, it is immediately re-opened in a deletes history container.

### Expected behavior

The behavior of automatic mode should not be influenced by whether or not the temporary container deletes history.

### Steps to reproduce

1. Enable Automatic Mode and Delete History containers by default.
2. Open a new tab.
3. Notice that the tab is immediately re-opened in a container in violation of the pref in Advanced -> General.

### Debug Log

[debug.txt](https://github.com/stoically/firefox-add-on-temporary-containers/files/1735228/debug.txt)

**Comment by stoically** [comment]
Hi, thanks for the exemplary report. Unfortunately this is necessary to avoid that "Deletes History Temporary Containers" leave traces of the opened URLs in "recently closed tabs". If you open a new tab in "Automatic Mode on navigation" with regular Temporary Containers, then navigate to example.com, close the tab, wait for the removal of the container and then click Ctrl+Shift+T or on the "about:newtab" tab in "recently closed tabs" you'll see the URL you initially navigated to. That's why I force reopening in case of "Deletes History Temporary Containers".

I've added a tooltip to the Advanced Automatic Mode preference.

**Comment by chiraag-nataraj** [comment]
Thanks @stoically for the explanation. Do I at least get bonus points for the debug log? :joy:
