### ISSUE TITLE
Container Count

### ISSUE THREAD

**Issue by sfeary** [stoically/firefox-add-on-temporary-containers#6]
Hopefully it's a simple request, but when a temp container is closed decrease the counter used in the name. Right now I have only one temp container and its number is 6, its just a minor nitpick but I was looking for non-existent containers when I came back to my workstation and forgot what I had open as the container number was up to 6!

**Comment by stoically** [comment]
Decreasing the Counter for every closed Temp Container that gets closed is a bit problematic because you would end up with e.g. the following Scenario:
- Open four Temp Container
- Close two Temp Containers
- Counter decreases from 4 to 2
- Open new Temp Container
- Now you have two Temp Containers with the name "tmp2"

What I could do is to reset the counter to 1 after the last Temp Container gets closed. Would that work for you? Do you maybe have another idea how to handle this? Cheers!

**Comment by sfeary** [comment]
Ye the counter wouldn't work as you described, maybe an array with the number and the container as key pairs. When a container closes, and a new one is open see if there is a lower number available and take it and if not just add to the end? Containers on the go works like this but the code is obfuscated so I can't see how he manages it.

**Comment by stoically** [comment]
Oh ok, so freeing up Container Numbers and reusing them - yeah, I guess what would work. Will introduce that as a Preference. Thanks for the suggestion!

**Comment by sfeary** [comment]
Great thanks!

**Comment by stoically** [comment]
Just published 0.11 with the "Keep counting" or "Reuse available Numbers" Preference. Keep in mind that after closing the last Tab in a Temporary Container it takes ~0.5s for it to get removed and sometimes removing doesn't work immediately. So Numbers might not be available for reuse directly but eventually. Hope you like it. Cheers!
