### ISSUE TITLE
Sites which track outgoing clicks won't open in new container

### ISSUE THREAD

**Issue by nemequ** [stoically/firefox-add-on-temporary-containers#7]
Right now, ctrl+click and middle-click will only create a new container if the link is to a different domain, but some sites (e.g., Reddit) replace links with an intermediary page on their own domain which then redirects to the destination so they can track outgoing clicks.

IMHO there should be a way to force a link to open in a new container that's a bit easier than using the context menu. My suggestion would be to keep middle-click as-is, but ctrl+click would always create a new container, but I'd also be okay with a configuration option to always open new tabs in new containers (as long as option to open a new tab in the current container in the context menu remains).

**Comment by stoically** [comment]
Hi, yeah, you're absolutely right, I guess a lot of sites do that. I'll change that behavior back so that it won't check the Domain but instead always open in new Temporary Container. On top of that I'll introduce preferences to deactivate the behavior completely for one or both of the mouse-clicks and to deactivate it for Domain-Patterns. That should cover all of your suggestions - let me know if not. Thanks for the feedback.

**Comment by stoically** [comment]
Just published Version 0.13 with said changes and preferences. If there's something missing or not working as expected, please let me know.
