### ISSUE TITLE
Icon visibility issues

### ISSUE THREAD

**Issue by Gitoffthelawn** [stoically/firefox-add-on-temporary-containers#9]
Thank you for the excellent extension!

The toolbar button is always a light gray color, which is hard to discern, especially when using lightweight themes.   IIRC, a light and dark icon are supposed to be supplied by the extension.

Also, I'm guessing it's supposed to look a little bit like an alarm clock, but I would prefer just a circle (or square) with a plus sign in it.

Containers on the Go extension (https://addons.mozilla.org/firefox/addon/containers-on-the-go/) has a nice easy-to-see icon, regardless of the theme being used.

**Comment by stoically** [comment]
The Add-on does provide a dark and light icon, you can see the difference when switching between the Default and Default Light Theme. But since I optimized it for the default Tabstrip which is dark, it'll look not that good if you have a Theme that's based on the Default Theme and has a light Tabstrip or just move it to the other BrowserActions. Also you can't change the Icon based on whether it's placed in the Tabstrip or BrowserAction area - native Firefox Icons (and the Multi-Account Containers one) can do that, normal Add-ons cannot.

So yeah, I'm actually not sure how to handle this - personally I don't want to make the Icon blue-ish or red-ish too, since I feel that's too much - but I will try it nevertheless and see how it looks.

Yes, it's a stop watch, indicating that the container will only run for a certain time - I don't feel like changing that, sorry.

**Comment by stoically** [comment]
Actually, now that I thought about it, changing it to just a circle might look cleaner - and circles are commonly used to indicate "Loading" - so you could say at one point the container "stops loading", hehe. I'll definitely test that.

Thanks for taking the time to open the Issue!

**Comment by Gitoffthelawn** [comment]
> Yes, it's a stop watch, indicating that the container will only run for a certain time.

Just to clarify, they aren't actually time-based, are they?  The container stays open until the user closes all the tabs in the container, correct?

**Comment by stoically** [comment]
That's correct

**Comment by Gitoffthelawn** [comment]
Would love to see a more visible and simpler icon!

**Comment by stoically** [comment]
I played around a bit and came up with this:

![image](https://user-images.githubusercontent.com/29637501/35484615-925b310a-0452-11e8-9574-30c549b53172.png)

![image](https://user-images.githubusercontent.com/29637501/35484622-a04c0924-0452-11e8-8c87-2a6bf7835fe6.png)

What do you think?

**Comment by Gitoffthelawn** [comment]
I like it a lot, except for the color red (unless that changes dynamically to match the color of the container... in which case, cool!).

To me, red means "stop" or "error".  I think blue or black would be a more suitable choice.  Or, allow the user to choose the color.

**Comment by stoically** [comment]
Afaik it's not possible to dynamically change the BrowserAction Icon - so no, it doesn't adapt to the container color and it isn't possible to let the user choose a color.

I mean, it's more of a orange-ish and if I look at my current BrowserAction Area

![image](https://user-images.githubusercontent.com/29637501/35485283-988e589e-045d-11e8-9f78-d3da0c657413.png)

uBlock, Cookie Auto Delete and FoxyProxy all have a red/orange theme. Also it's the same color als the default settings for temporary containers.

I don't want to use blue since Container on the Go already uses that.

**Comment by stoically** [comment]
Ok, turns out I was wrong about not being able to change the BrowserAction Icon - there's an [setIcon API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/setIcon) to do it, TIL.

I'm going to keep the grey as default (although I'll change the default location from tabstrip to navbar (browseraction area)) and provide a preference to configure orange/red-ish and blue (the blue from the containers colors?) as alternatives. Sounds good?

**Comment by Gitoffthelawn** [comment]
Sounds great!

Are you going to create separate icons, or adjust the hue of a single one on the fly?  The advantage to the latter is that you can allow the user to adjust the color; the downside is that is probably takes a little more processing time each time the toolbar is painted.

**Comment by stoically** [comment]
I'll just create two static versions. Will accept pull requests for custom colors though.

**Comment by Gitoffthelawn** [comment]
I see you're using inkscape vector images.  In another project (and I apologize that I don't recall which one), we discussed whether or not to use vector images for toolbar icons.

I can't find that thread right now... but, do you happen to know if using vector images introduces performance issues during the toolbar paint cycle?

**Comment by stoically** [comment]
Just published version 0.28 with the BrowserAction Icon Color preference. Hope you like it.

Never measured paint cycles regarding vector images, so no clue, sorry.

**Comment by Gitoffthelawn** [comment]
Just downloaded 0.28.  Looks great!  Thanks!  How about a simple white icon and a simple black icon?

**Comment by stoically** [comment]
Sure, why not. Added and will be included in the next version.

**Comment by Gitoffthelawn** [comment]
Thanks!  Looking forward to it!

I like the blue icon, but with my greenish theme, it is not visible.  I wonder if adding a white outline around the icon would make it more visible.  Food for thought.

**Comment by stoically** [comment]
FYI, just published version 0.29

**Comment by Gitoffthelawn** [comment]
Got it.  Love it.  It's fantastic!  Thank you.

How about adding a light yellow one?  It would stand out a little and look like it was highlighted.  Something like rgb(255,255,150).

**Comment by stoically** [comment]
Happy you like it. Maybe you want to look into opening a Pull request for new colors? That'd be neat. Thanks.
